# Site settings
title: Clearview Flying Club
email: gokoyev@gmail.com
url: http://clearviewflyingclub.club/
description: "A member-owned non-profit flying club with a fleet of two well-maintained, affordably-priced aircraft."
address: "526 Oak Tree Road, Westminster, MD, 21157"
# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#333333'
  links: '#219ab3'

# Footer settings
footer: Clearview Flying Club

# Build settings
markdown: kramdown
permalink: pretty
